using System;
using System.Collections.Generic;
using System.Numerics;
using System.Text;
using BepInEx.Configuration;
using UnityEngine;

namespace ErenshorQoL
{
    public class Utilities
    {
        internal static void ApplyConfig()
        {

            ErenshorQoLMod._configApplied = true;
        }

        internal static void GenerateConfigs()
        {
            ErenshorQoLMod.AutoLootToggle = ErenshorQoLMod.context.config("1 - AutoLoot", "Enable AutoLoot", ErenshorQoLMod.Toggle.On, "This file is automatically generated by the Erenshor Quality of Life Mods plugin and is used to configure various mod features. You can revert to the defaults if you experience issues.\nEnable automatic looting within the LootDistance?");
            ErenshorQoLMod.AutoLootDistance = ErenshorQoLMod.context.config("1 - AutoLoot", "Auto Loot Distance", 30f, "Distance to automatically loot items from defeated enemies. Acceptable Range <float> 5-10000");
            ErenshorQoLMod.QoLCommandsToggle = ErenshorQoLMod.context.config("2 - QoL Commands", "Enable QoL Commands", ErenshorQoLMod.Toggle.On, "Enable additional Quality of Life commands like /bank, /sell, /auction, updated /help etc.");
            ErenshorQoLMod.AutoAttackToggle = ErenshorQoLMod.context.config("3 - Auto Attack", "Enable Auto Attack", ErenshorQoLMod.Toggle.On, "Enable automatically turning on auto-attack.");
            ErenshorQoLMod.AutoAttackOnSkillToggle = ErenshorQoLMod.context.config("3 - Auto Attack", "Auto Attack on Skill Use", ErenshorQoLMod.Toggle.On, "Automatically start attacking when a skill is used.");
            //ErenshorQoLMod.AutoAttackOnSpellToggle = ErenshorQoLMod.context.config("3 - Auto Attack", "Auto Attack on Spell Cast", ErenshorQoLMod.Toggle.Off, "(not yet implemented) Automatically start attacking when a spell is cast.");
            //ErenshorQoLMod.AutoAttackOnGroupAttackToggle = ErenshorQoLMod.context.config("3 - Auto Attack", "Auto Attack on Group Attack Command", ErenshorQoLMod.Toggle.Off, "(not yet implemented) Automatically start attacking when a group attack command is issued.");
            //ErenshorQoLMod.AutoAttackOnPetAttackToggle = ErenshorQoLMod.context.config("3 - Auto Attack", "Auto Attack on Pet Attack Command", ErenshorQoLMod.Toggle.Off, "(not yet implemented) Automatically start attacking when a pet attack command is issued.");
            ErenshorQoLMod.AutoPetToggle = ErenshorQoLMod.context.config("4 - Auto Pet", "Enable Auto Pet Command", ErenshorQoLMod.Toggle.On, "Enable automatically commanding the pet to attack.");
            ErenshorQoLMod.AutoPetOnSkillToggle = ErenshorQoLMod.context.config("4 - Auto Pet", "Auto Pet Command on Skill Use", ErenshorQoLMod.Toggle.On, "Automatically command the pet to attack when a skill is used.");
            //ErenshorQoLMod.AutoPetOnSpellToggle = ErenshorQoLMod.context.config("4 - Auto Pet", "Auto Pet Command on Spell Cast", ErenshorQoLMod.Toggle.Off, "(not yet implemented) Automatically command the pet to attack when a spell is cast.");
            //ErenshorQoLMod.AutoPetOnGroupAttackToggle = ErenshorQoLMod.context.config("4 - Auto Pet", "Auto Pet Command on Group Attack", ErenshorQoLMod.Toggle.Off, "(not yet implemented) Automatically command the pet to attack when a group attack command is issued.");
            ErenshorQoLMod.AutoPetOnAutoAttackToggle = ErenshorQoLMod.context.config("4 - Auto Pet", "Auto Pet Command on Auto Attack", ErenshorQoLMod.Toggle.On, "Automatically command the pet to attack when auto-attack is enabled.");
            //ErenshorQoLMod.AutoGroupAttackToggle = ErenshorQoLMod.context.config("5 - Auto Group Attack", "Enable Auto Group Attack Command", ErenshorQoLMod.Toggle.Off, "(not yet implemented) Enable automatically commanding the group to attack.");
            //ErenshorQoLMod.AutoGroupAttackOnSkillToggle = ErenshorQoLMod.context.config("5 - Auto Group Attack", "Auto Group Attack on Skill Use", ErenshorQoLMod.Toggle.Off, "(not yet implemented) Automatically command the group to attack when a skill is used.");
            //ErenshorQoLMod.AutoGroupAttackOnSpellToggle = ErenshorQoLMod.context.config("5 - Auto Group Attack", "Auto Group Attack on Spell Cast", ErenshorQoLMod.Toggle.Off, "(not yet implemented) Automatically command the group to attack when a spell is cast.");
            //ErenshorQoLMod.AutoGroupAttackOnPetAttackToggle = ErenshorQoLMod.context.config("5 - Auto Group Attack", "Auto Group Attack on Pet Attack Command", ErenshorQoLMod.Toggle.Off, "(not yet implemented) Automatically command the group to attack when a pet attack command is issued.");
            //ErenshorQoLMod.AutoGroupAttackOnAutoAttackToggle = ErenshorQoLMod.context.config("5 - Auto Group Attack", "Auto Group Attack on Auto Attack", ErenshorQoLMod.Toggle.Off, "(not yet implemented) Automatically command the group to attack when auto-attack is enabled.");
            //ErenshorQoLMod.AutoRunToggle = ErenshorQoLMod.context.config("6 - Auto Run", "Enable Auto Run", ErenshorQoLMod.Toggle.Off, "(not yet implemented) Automatically run while enabled");
            //ErenshorQoLMod.AutoRunKey = ErenshorQoLMod.context.config("6 - Auto Run", "Auto Run Key", new KeyboardShortcut(KeyCode.Break), new ConfigDescription("Key(s) used to toggle Auto Run. Use https://docs.unity3d.com/Manual/ConventionalGameInput.html", new ErenshorQoLMod.AcceptableShortcuts()));
        }
    }
}
